### ISSUE TITLE
Incompatible with "'Slight' Gui Modifications" mod

### ISSUE THREAD

**Issue by SusStew** [LudoCrypt/Vistas#12]
**This mod will not load when used with the ['Slight' Gui Modifications mod](https://github.com/shedaniel/slight-gui-modifications)**.

**Log here** (game did not produce crash report, only log): https://pastebin.com/3eYXGUaq

**Mod list** (tested with only the two mods and their dependencies to make sure something else wasn't causing it):
- architectury-2.4.26-fabric.jar
- cloth-api-2.0.54.jar
- cloth-config-5.0.38-fabric.jar
- fabric-api-0.38.2+1.17.jar
- modmenu-2.0.5.jar
- slight-gui-modifications-2.0.1.jar
- vistas-1.4.4.jar

When both are enabled, the game crashes. When one or the other is enabled, the game does not crash.

**Comment by Ascellayn** [comment]
Confirmed that this mod does crash Minecraft with Vistas.

**Comment by LudoCrypt** [comment]
Fixed in latest commit
