### ISSUE TITLE
Chunks are invisible when making panorama using H keybind

### ISSUE THREAD

**Issue by helpimnotdrowning** [LudoCrypt/Vistas#13]
Many chunks don't render at all when using H to create a panorama. Chunks directly behind me (pic below) and infront seem to load fine,
![Chunks behind me](https://user-images.githubusercontent.com/35247379/132960869-8f36a13e-0dbb-491f-95fd-2090212aed9c.png), but chunks to my left (pic below), right and directly below me (second pic below)
![Chunks to my left](https://user-images.githubusercontent.com/35247379/132960893-0101f6e5-65ee-4870-af87-04eb6b223011.png) 
![And directly under me](https://user-images.githubusercontent.com/35247379/132960915-d218e7d8-0113-46e5-aa18-488d63267019.png)
are invisible.

Using:
- Java 16
- Minecraft 1.17.1
- Sodium 0.3.2 build 7
- Vistas 1.4.4
- Fabric API 0.36.1 1.17.1

**Comment by LudoCrypt** [comment]
This is an issue with sodium not rendering chunks the user isn't seeing, Minecraft also does this. Unfortunately i don't think there is a fix to this one unless i make panorama screenshots more manual.

**Comment by helpimnotdrowning** [comment]
I was thinking there could be a short delay added inbetween when the direction the player is facing is changed and when the screenshot is taken, maybe like .5/1 seconds?

**Comment by LudoCrypt** [comment]
Fixed in most recent commit
