### ISSUE TITLE
Don't include cloth config and fabric api

### ISSUE THREAD

**Issue by Qendolin** [LudoCrypt/Vistas#18]
Including those mods adds 835 kB ( **93%** ) to your mod's jar and it doesn't make any sense as most players already have fabric api and cloth config in their mod folders. So use `modImplementation` istead of `includeMod` and add them to the `depends` section in your `fabric.mod.json`.

**Comment by LudoCrypt** [comment]
We do that so nobody has to download them separately.

**Comment by NeusFear** [comment]
for fabric api though you should only include the modules you need instead of the whole mod. I wouldn't close this just yet @LudoCrypt
