### ISSUE TITLE
Update to 1.18.2

### ISSUE THREAD

**Issue by osfanbuff63** [LudoCrypt/Vistas#23]
Currently, this mod, when used with a list of mods (that I will list below) instantly crashes Minecraft when loading 1.18.2 (of course with Fabric installed :P). I would help out, but the one change I tried to make just completely broke Gradle when trying to build. I will attach the latest.log, as well as a mod list below. I'm not very experienced with this sort of stuff, just waiting on this mod (and one other) to move to 1.18.2.

I hope something will be able to be done with this, as I love this mod, it's so useful :D 

[latest.log](https://github.com/TerraformersMC/Vistas/files/8380414/latest.log)

Mods:
- Fabric Loader v0.13.3
- Boosted Brightness v2.1.1
- Cloth Config v6.2.57
- Effective v1.2 (from [this fork](https://github.com/qruet/Effective/tree/1.18.2-dev))
- Fabric API v0.46.1
- Illuminations v1.10.3 (from [this fork](https://github.com/North-West-Wind/Illuminations))
- LazyDFU v0.1.2
- MaLiLib v0.12.1
- MiniHud v0.22.0
- Mod Menu 3.1.0
- NotEnoughAnimations v1.5.0
- OptiFabric v1.13.0
- OptiFine HD_U_H6
- Replay Mod v2.6.4
- Shulker Box Tooltip v3.0.7
- Starlight v1.0.2
- Vistas v2.1.0
- WorldEdit v7.2.10

**Comment by gniftygnome** [comment]
You don't need all those mods, though.  Just Vistas and Fabric API will do it.

```
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_1745 was not located in the target class net.minecraft.class_310. Using refmap vistas-refmap.json
```

**Comment by gniftygnome** [comment]
I think it's a small change.  Submitted PR #24.

**Comment by osfanbuff63** [comment]
#24 was finally merged, closing.
