### ISSUE TITLE
Error when trying to add menu music.

### ISSUE THREAD

**Issue by AnyaPizza** [LudoCrypt/Vistas#36]
I downloaded the Back To Past example pack and added my own panorama which works perfectly fine. But when I tried adding a song I get this error when pack is loaded. 

[17:14:54] [Render thread/ERROR]: Signature is missing from Property textures
[17:15:36] [Render thread/ERROR]: Signature is missing from Property textures
[17:15:37] [Render thread/ERROR]: Signature is missing from Property textures
[17:15:38] [Render thread/ERROR]: Signature is missing from Property textures
[17:15:39] [Render thread/ERROR]: Signature is missing from Property textures
[17:15:40] [Render thread/ERROR]: Signature is missing from Property textures

**Comment by haykam821** [comment]
The logs you posted should be unrelated; they're from [a vanilla bug](https://bugs.mojang.com/browse/MC-264966) regarding player heads.

**Comment by AnyaPizza** [comment]
> The logs you posted should be unrelated; they're from [a vanilla bug](https://bugs.mojang.com/browse/MC-264966) regarding player heads.

Hmm, weird. I only get this error when I run this mod and with the pack I made. I'm just on the main menu so no player heads are present.

**Comment by AnyaPizza** [comment]
I realized the issue was with another mod. I apologize. However, I'm still unable to get the music to work even though I'm sure I made the pack correctly.

**Comment by gniftygnome** [comment]
Yeah, I believe you.  I don't have a test case for music.  :laughing:

**Comment by gniftygnome** [comment]
I looked into this and I'm pretty sure it's completely broken as presently implemented.  And I have no idea how to fix it.  You have to add SoundEvent objects to the registry from a mod, so to start with, using just a resourcepack is not going to work.  Furthermore, right now it seems the codec used to load the SoundEvent registry entry via the key in panoramas.json fails to load all keys for some reason I'm not seeing.  :(  I may come back to this again another day but I spent most of today beating my head against it to no avail.

**Comment by AnyaPizza** [comment]
> I looked into this and I'm pretty sure it's completely broken as presently implemented.  And I have no idea how to fix it.  You have to add SoundEvent objects to the registry from a mod, so to start with, using just a resourcepack is not going to work.  Furthermore, right now it seems the codec used to load the SoundEvent registry entry via the key in panoramas.json fails to load all keys for some reason I'm not seeing.  :(  I may come back to this again another day but I spent most of today beating my head against it to no avail.

Interesting. Well hopefully one day we'll have a working system. Thanks for looking into it! :)

**Comment by gniftygnome** [comment]
I came up with a cursed hack to avoid having to register the SoundEvents.  Probably maybe possibly somewhat hopefully this will resolve the issue until the next thing Mojang breaks.
