### ISSUE TITLE
[Bug] The panoramas don't load 

### ISSUE THREAD

**Issue by asteroidb12** [LudoCrypt/Vistas#4]
I am using the extrapanoramas resource pack. It shows the default panorama with a gradient on top instead of what's included in the resource pack. Messing with the settings don't work either.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/68461874/107329470-10bd1380-6a65-11eb-8c9b-0832161363db.png)

Thank you.

**Comment by Prospector** [comment]
I'm unable to reproduce, it works fine for me. Do you have any other mods installed that might be messing with the panorama? Whatever is adding that gradient is likely what is causing the issue. Could you also send a log so I could inspect it?

![image](https://user-images.githubusercontent.com/6166773/107331287-84f8b680-6a67-11eb-946d-af8fd639f4e9.png)

**Comment by asteroidb12** [comment]
Alright, I forgot to do this ealier.
Here is the mod list:
![image](https://user-images.githubusercontent.com/68461874/107333055-ce4a0580-6a69-11eb-8308-c0e2112fff13.png)

Here is the log:
[latest.log](https://github.com/TerraformersMC/Vistas/files/5949740/latest.log)

**Comment by Prospector** [comment]
Oh, I bet it is `bedrockify`. Can you try without that mod?

**Comment by asteroidb12** [comment]
It works after taking out bedrockify. Although, will this be a temporary solution?
![image](https://user-images.githubusercontent.com/68461874/107342984-b8424200-6a75-11eb-94ae-be70b0c3f1f2.png)

**Comment by Prospector** [comment]
I will see about figuring out some way to make this work, it's hard with how invasive of a mod Bedrockify is.

**Comment by Prospector** [comment]
I've make a PR to fix this on Bedrockify's end: https://github.com/juancarloscp52/BedrockIfy/pull/58
