### ISSUE TITLE
Feature Request: Easily Take a Panorama

### ISSUE THREAD

**Issue by greensad** [LudoCrypt/Vistas#5]
Ability to take a panorama in game using a single keystroke, similar to the now abandoned [Runorama](https://www.curseforge.com/minecraft/mc-mods/runorama).

**Comment by Prospector** [comment]
Vistas actually has this feature, check your controls for the keybinding

**Comment by greensad** [comment]
Oh that's wonderful news. I didn't get that from the curseforge description or a brief read of the documentation so I assumed Vistas was simply a tool for compiling and implementing panoramas. It may be worth considering including this information on curseforge as well so that this function is more clear. In any case, thank you for the reply!
