### ISSUE TITLE
Panoramas not loading

### ISSUE THREAD

**Issue by Hardfg5000** [LudoCrypt/Vistas#6]
Hello, for some reason no matter what I do, no panoramas will load. It's a very similar issue to #4 but I don't have Bedrockify. Here is a list of mods I do have though: 
![Capture](https://user-images.githubusercontent.com/35854067/113463121-a8126780-9413-11eb-897b-34e57a8d5012.PNG)

**Comment by LudoCrypt** [comment]
Can you please provide your latest.log for when you play with the mod? Maybe also try without optifine and see if it works then. Do make sure you also have the resourcepack actually selected.

**Comment by Hardfg5000** [comment]
Hello, 

[latest.log](https://github.com/TerraformersMC/Vistas/files/6255530/latest.log) (Optifine)
[latest.log](https://github.com/TerraformersMC/Vistas/files/6255547/latest.log) (no Optifine, and disabled the resourcepacks)

I have it loaded:![image](https://user-images.githubusercontent.com/35854067/113523652-8abad600-9598-11eb-8b89-78f1b8ea16b6.png)

(I also tried the other resource pack on the Curseforge page and no luck)

**Comment by Hardfg5000** [comment]
uhhhh it works all of a sudden, may have been a one off tho, am checking now

**Comment by LudoCrypt** [comment]
Hm, if any issue, it would be that the resource pack is invalid. Not sure what would cause this though.

**Comment by Hardfg5000** [comment]
I tried to add a folder to an existing resource pack and it doesn't work anymore (did this for testing, will make own once this is resolved)
{
	"classic": {
		"name": "blast_to_past:classic",
		"panoramaId": "blast_to_past:panoramas/classic/panorama"
	},
	"ocean": {
		"name": "blast_to_past:ocean",
		"panoramaId": "blast_to_past:panoramas/ocean/panorama"
	},
	"bees": {
		"name": "blast_to_past:bees",
		"panoramaId": "blast_to_past:panoramas/bees/panorama"
	},
	"village": {
		"name": "blast_to_past:village",
		"panoramaId": "blast_to_past:panoramas/village/panorama"
	}
	"bsu": {
		"name": "blast_to_past:bsu",
		"panoramaId": "blast_to_past:panoramas/bsu/panorama"
	}
}
![image](https://user-images.githubusercontent.com/35854067/113524699-e63c9200-959f-11eb-88fb-0314c3236657.png)
But when I redownloaded the original, it worked all of a sudden and Optifine is loaded. Perhaps that's why?

**Comment by LudoCrypt** [comment]
Maybe the file got corrupted in downloading. Anyways, if there's no issue, wonderful!
