### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ghost** [LudoCrypt/Vistas#8]
my game crashed at startup for some reason with this mod, here is crash-report: https://hastebin.app/60a5bb15706e45001dfb023e

**Comment by LudoCrypt** [comment]
Try with the latest version, if it still doesnt work, send the latest.log and the resourcepacks you have used

**Comment by ghost** [comment]
> Try with the latest version, if it still doesnt work, send the latest.log and the resourcepacks you have used

still not working, here is my latest.log https://hastebin.app/60aad754706e45001dfb0242

**Comment by LudoCrypt** [comment]
Your problem is Meteor Client, don't use hacks.
